[build-system]
requires = ["setuptools>=45", "wheel", "Cython>=0.29", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "cythonaligner"
version = "1.0"
description = "Cython implementation of Needleman-Wunsch"
requires-python = ">=3.7"
dependencies = ["numpy"]
